### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by agorshkov23** [Mikhus/domurl#16]
Hello!
You didn't think about language support for [TypeScript](http://typescriptlang.org)? I could write a file jsurl.d.ts, and push it to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository which would be a description of the library functions.

**Comment by Mikhus** [comment]
Hello, actually I'm not using TypeScript, but if you have a good idea how
to do support of it it would be great - you are absolutely free to
contribute, of course.

All kind regards,
Mike

**Comment by Mikhus** [comment]
Seems DefinitelyTyped repo should be updated due to version 2.0 API changes and library rename... 

Best regards,
Mike

**Comment by agorshkov23** [comment]
Thank you, I'll do it soon :)

**Comment by agorshkov23** [comment]
@Mikhus, Thank you, I'll do it soon :)

**Comment by Mikhus** [comment]
@agorshkov23 Thanks, Alex, I would be very appreciate for that!

**Comment by Mikhus** [comment]
PR for DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10588

**Comment by Mikhus** [comment]
PR merged, closing...
