### ISSUE TITLE
Cannot find the package on npm registry

### ISSUE THREAD

**Issue by ssidorchick** [Mikhus/domurl#19]
In our company we are migrating away from bower in favor of npm registry. Could you publish the package on npm?

**Comment by Mikhus** [comment]
It's browser use only, so I don't think this is a good idea...

**Comment by ssidorchick** [comment]
Some popular front end libraries and frameworks like jquery, backbone, angular, react available on npm. Defined as commonjs module it's easier to import dependencies using webpack with ES6 syntax.

**Comment by Mikhus** [comment]
Well, it's a deal...

**Comment by Mikhus** [comment]
Finally I decided to rename lib to domurl. Now it is available through NPM, jamjs and bower as well. Please, enjoy!

**Comment by ssidorchick** [comment]
You could use scope for the package, but it makes the full name longer and it's a paid npm feature. In any case thanks a lot for the changes.
