### ISSUE TITLE
Doesn't actually manipulate the URL?

### ISSUE THREAD

**Issue by sicdigital** [Mikhus/domurl#20]
Was looking for something similar to your library. I'm looking through the code and just want to confirm, this only allows you to update the object created by instantiating the class. This doesn't actually update the URL when changes to the class are made? If this is the case it would be interesting to add some HTML5 history support to update the actual URL when changes are made to the domurl object. Reading the description of the project I assumed this was what it actually did. 

I'm going to be modifying the library for my own use, to update the URL, if you're interested I'll try to form a complete solution and submit a pull request when I'm done. If not I'll just add the stuff I need in my project. 

Thanks for taking the time to make this thing and sharing it 👍

**Comment by Mikhus** [comment]
Hi @sicdigital 
Thanks for your interest in domurl. Absolutely true that this library does not provide any functionality to actual manipulation of browser history object. It is only about parsing and manipulating URL strings.
What you are looking for is out of the scope of domurl and I'm not sure it should be in the scope ever.

**Comment by alexandernst** [comment]
@Mikhus sorry for spawning such an old issue. Given the fact that manipulating the URL could be easily implemented with pushState / replaceState, and given the fact that the target user of this library is likely to be willing to reflect the changes back to the actual URL, why not implement it?

Maybe something like 

```
u = new Url;
u.query.foo = "bar";
u.apply();  // <-- new method
```

This won't break any current functionality and will add an extra feature that will likely be used by current users.
