### ISSUE TITLE
localhost:port not supported

### ISSUE THREAD

**Issue by TrevorSayre** [Mikhus/domurl#21]
```
var url = new Url("localhost:9001");
console.log(url, '' + url);
```

```
Url {protocol: "localhost", host: "", port: "", path: "/9001", query: QueryString…}
hash:""
host:""
pass:""
path:"/9001"
port:""
protocol:"localhost"
query:QueryString
user:""
__proto__:Object

localhost:///9001
```

**Comment by Mikhus** [comment]
This is absolutely expected behavior. domurl parses URLS the same way as browser does. For example, 
if you will try to build a link <a href="localhost:9001"> this will cause almost similar problems for you.

**Comment by TrevorSayre** [comment]
If I make a link `<a href="localhost:9001">test</a>` I do not get similar problems. This is not how a URL is parsed in modern browsers: http://jsbin.com/nohohexime/edit?html,output
