### ISSUE TITLE
When passing a relative url into Url() and converting to string, the current pages path is included

### ISSUE THREAD

**Issue by brookscom4580** [Mikhus/domurl#23]
I've written a simple function that cleans some query strings out of any provide url string:
`function sanitizeURL(url) {
		var url = new Url(url);
		if(url.query["reload"]) {
			delete url.query["reload"]
		}
		if(url.query["forceReload"]) {
			delete url.query["forceReload"]
		}
		if(url.query["device"]) {
			delete url.query["device"]
		}
		if(url.query["testwebid"]) {
			delete url.query["testwebid"]
		}
		if(url.query["testWebId"]) {
			delete url.query["testWebId"]
		}
		if(url.query["testWebID"]) {
			delete url.query["testWebID"]
		}
		if(url.query["timetravel"]) {
			delete url.query["timetravel"]
		}
		return url.toString();
	}`
but when I add run with a relative url string the whole pages path is returned:
sanitizeURL("SearchResults?search=new&make=Buick&year=2016&forceReload=true")

What's returned:
"file:///Volumes/Macintosh%20HD/Users/brooksg/SearchResults?search=new&make=Buick&year=2016"

Expecting:
"SearchResults?search=new&make=Buick&year=2016"

Is there anyway around this or is this a bug?

**Comment by Mikhus** [comment]
It's an expected behavior, because it was initially designed to transform any given URL to an absolute form. By the way I can understand your need, so I added an option to constructor call which will tell to keep source URL form. It will be implemented in the next release version.
Thank you for contribution!

**Comment by Mikhus** [comment]
Implemented in version 2.1.2

**Comment by brookscom4580** [comment]
Thank you so much!
