### ISSUE TITLE
Undefined variables included in query string

### ISSUE THREAD

**Issue by ryanitus** [Mikhus/domurl#30]
Variables with a value of undefined are included in the query string.

For example:

var url = new Url();
var url2 = new Url();
url2.clearQuery();
url2.query["var"] = url.query["var"];

ur2.query.toString()

If "var" doesn't exist in the query string, this will print out "var=undefined".  Could undefined variables be ignored?

**Comment by Mikhus** [comment]
fixed in v2.2.0
