### ISSUE TITLE
Does not work with arrays (e.g. https://example.com/?computer[desktop]=Mac)

### ISSUE THREAD

**Issue by W3Extensions** [Mikhus/domurl#33]
```
var u2 = new Url("https://example.com/");
u2.query["computer"] = {};
u2.query["computer"]["desktop"] = "Mac";	
alert(u2); 
```

The result should be this...
https://example.com/?computer[desktop]=Mac

Instead, I get this...
https://example.com/?computer=%5Bobject%20Object%5D

Also, when I parse a URL that looks like....
https://example.com/?computer[desktop]=Mac

...Inspecting the object in the console should look like return something like...
```
Computer: Object
	desktop: "Mac"
```
	

Instead I get this...
`computer[desktop]: "Mac"`

"desktop" isn't recognized as an object inside of "computer". "computer[desktop]" is simply used as the key like any other string.

**Comment by Mikhus** [comment]
Exactly, as far as there is no any existing standard telling us that query string is anyhing different from key=value. Only in favor of not loosing data it accepts the several keys with the same name to be an array, no other "specific" parsing (PHP-like or whatever) was not supposed to be supported...

**Comment by joker-777** [comment]
@Mikhus I would be great if your library would support different kinds of array formats like [this library does]((https://github.com/sindresorhus/query-string#arrayformat).
