### ISSUE TITLE
Current url, once initialized, is cached forever and never reflects changes to window.location.href

### ISSUE THREAD

**Issue by jwhiting** [Mikhus/domurl#35]
When initializing with `new Url()`, this module uses the current `window.location.href` by default, and then caches it forever in the module's closure/namespace. After that, even when the `window.location.href` changes, the module will still use the old/incorrect cached value on `new Url()` invocations:

    var url = new Url();
    url.hash = "somehash";
    window.location.href = url.toString()
    var url2 = new Url();
    url2.hash // empty, should be "somehash"

Also note that in apps using pushState (i.e. most SPAs these days), much more than the hash will change. The above is just one way to demonstrate the bug in a non-pushState navigation without causing a page reload.

**Comment by JSteunou** [comment]
Same here. This is a critical issue I think. I'm using `replaceState` some times, and after that `new Url()` is just not good.

**Comment by Mikhus** [comment]
Fix published as v2.1.9, thank you for contribution!

**Comment by JSteunou** [comment]
You are welcome, thank you for the quick patch release :)
