### ISSUE TITLE
Issues when square brackets are used in parameter name

### ISSUE THREAD

**Issue by osuagwu** [Mikhus/domurl#45]
Issues when square brackets are used in parameter name.
e,g it cannot handle:
 /products/?items[]=e&items[]=f

It just see 'item[]' and 'item'

**Comment by Mikhus** [comment]
I can't see any problems with parsing. Query contains property `'items[]'` as an array of 2 values `['e', 'f']` wich is absolutely expected correct parsing behavior, closing...

**Comment by besfahbod** [comment]
Hum... looks like we don't have unit-test for this. Probably worth having it now? (@osuagwu, wanna send a PR?)

**Comment by Mikhus** [comment]
Actually there is a test which checks array-like query params. Problem here is that this kind of questions raised usually by PHP devs, whom expect that parsing of query params must work exact that way PHP does it :)
Of course we can add specific test case parsing param names containing special chars as [] or {} or any others just to have an ability of quick check when such kind of questions raised over time
