### ISSUE TITLE
Small issues in encoding URLs with param values null and undefined

### ISSUE THREAD

**Issue by besfahbod** [Mikhus/domurl#46]
Looks like the changes in 1a605a573e4e205c00336463a82a77fac910cad5 have made some of the decoding and encoding behaviors asymmetric.

First, a loop on a valid URL causes value-less params to get lost. So, this doesn't pass:
```javascript
const urlString1 = "/?alice=123&bob=&carol";
const url1 = new Url(urlString1);
expect(String(url1)).toEqual(urlString1);
```
with error:
```javascript
    Expected: "/?alice=123&bob=&carol"
    Received: "/?alice=123&bob="
```

After decoding, this does pass:
```javascript
const urlString1 = "/?alice=123&bob=&carol";
const url1 = new Url(urlString1);
expect(url1.query["alice"]).toEqual("123");
expect(url1.query["bob"]).toEqual("");
expect(url1.query["carol"]).toBe(null);
expect(url1.query["dave"]).toBe(undefined);
```

So, the problem lays on the encoding side. With changing the encoding logic to:
- drop param if value is `undefined`, and
- keep param without value if the value is `null`,
then we can make sure using values returned from `.query` to reconstruct the URL would result in the original URL, hence passing the initial test.

What do you think?

**Comment by besfahbod** [comment]
Wdyt, @Mikhus?

If we are in agreement on the expected behavior, I might be able to send a PR for it.

**Comment by Mikhus** [comment]
Sounds legit. BTW, I'm curious about this:
```
expect(url1.query["bob"]).toEqual(" ");
```

I guess it should be:

```
expect(url1.query["bob"]).toEqual("");
```

**Comment by besfahbod** [comment]
Cool! Will send a PR soon.

Yeah, the space was a bad copy-paste. Updated the description.

**Comment by besfahbod** [comment]
Okay, https://github.com/Mikhus/domurl/pull/47 address the issue here, both for plain values and array values.

Would appreciate if you could make a cut after merge, @Mikhus. I should be able to give a hand with that, as well, if needed. Thanks! 😄
