### ISSUE TITLE
structured parameters not decoded

### ISSUE THREAD

**Issue by hawajrambo** [Mikhus/domurl#5]
var a={q:1, w:"w2", e:{ea:"123qwe", eb:"345asd"},  f:["qw", "er", 12], g:[{zx:123, vv:345}, {zxc:1234, cvb:3455}] };
var u=new Url("https://us:pw@xxx.com/path1/path2?" + decodeURIComponent($.param(a)) );

u.query.e  should return {ea:"123qwe", eb:"345asd"}

**Comment by Mikhus** [comment]
Related: #10
